server:
  port: 8080

spring:
  application:
    name: book-runner

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/book_runner_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 2000ms

# App-specific parameters
app:
  jwt:
    secret: ${JWT_SECRET:}
    expiration-ms: 86400000 # 24 hours
    refresh-expiration-ms: 604800000 # 7 days
  recsys:
    user-cold-start-threshold: 5
    item-cold-start-threshold: 5
    default-recommendation-limit: 10
    cache-ttl-hours: 2
